### ISSUE TITLE
Publish as jar library

### ISSUE THREAD

**Issue by joost-de-vries** [albuch/sbt-dependency-check#1]
I like your sbt plugin. Very useful.
Can you publish it to, say, Bintray or MavenCentral? 
That way we could use it as an sbt dependency...

**Comment by albuch** [comment]
Sure. I'll have a look at the process to get it into a public repo, probably Bintray as it's the recommended repo for sbt community plugins.
http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html

**Comment by albuch** [comment]
Released version 0.1.0 to Maven Central. Please report any issues or create a pull request.
