### ISSUE TITLE
Logs of org.apache.commons.jcs running dependencyCheck

### ISSUE THREAD

**Issue by reidrac** [albuch/sbt-dependency-check#102]
This is with 1.3.3. When running `dependencyCheck` taks there are multiple log lines from `org.apache.commons.jcs` that only add noise to the ouput.

Is there any way to supress those log lines?

Thanks!

**Comment by albuch** [comment]
This probably can only be achieved by hacking something into the plugin code, as JCS (which is a transitive dependency from depenency-check-core) does some strange logging stuff. The Maven plugin had the same issues and implemented a hack: https://github.com/jeremylong/DependencyCheck/issues/2072

**Comment by albuch** [comment]
Took quite some time to find the proper logger. The log entries will be removed in the next release.

**Comment by lawrenceong** [comment]
@albuch Tried this on version 2.0.0 and it seems to be having a lot of `org.apache.commons.jcs` logs still.  Am I missing something?  Steps taken:

* Create a new Scala Project using IntelliJ IDEA - SBT 1.2.8 + Scala 2.12.12
* Create a `project/plugins.sbt` file with the only content being `addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "2.0.0")`
* Run `sbt dependencyCheck`
