### ISSUE TITLE
Speciying CveURLs 

### ISSUE THREAD

**Issue by abdulahjamak-abh** [albuch/sbt-dependency-check#111]
Hi,

I am trying to set up the plugin as global, with local NIST mirror. I am having problems specifying the CveURLs in the _global.sbt_. I've tried several options, and always got errors (in similar format):

General approach:
`net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin.autoImport.dependencyCheckCveUrlModified := "https://..urlof-modified.json.gz"`
and god the error as 
`found   : String("...")
 required: Option[sbt.URL]
    (which expands to)  Option[java.net.URL]
net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin.autoImport.dependencyCheckCveUrlModified := "..."`
I've also tried setting the url as `url(s"..."),` `url("...")`, `Some(url(s"...")),` `Some(url("..."))`, `Optinos[url(s"...")]`. 

Can you please tell me how to specify the url?

P.S I am specifying both the dependencyCheckCveUrlModified and dependencyCheckCveUrlBase in the same way just different links.

**Comment by jortkoopmans** [comment]
Not sure if this helps you, but I specify as such (in build.sbt);

dependencyCheckCveUrlModified := Some(url("https://mymirror.local/nvdcve-1.0-modified.json.gz"))
dependencyCheckCveUrlBase := Some("https://mymirror.local/nvdcve-1.0-%d.json.gz")
