### ISSUE TITLE
.NET Assembly Analyzer could not be initialized 

### ISSUE THREAD

**Issue by himnsuk** [albuch/sbt-dependency-check#152]
I am getting below error when running on jenkins

`[pool-11-thread-6] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - ----------------------------------------------------

[pool-11-thread-6] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or add the path to dotnet core in the configuration.
[pool-11-thread-6] ERROR org.owasp.dependencycheck.analyzer.AssemblyAnalyzer - ----------------------------------------------------`

how can i fix this

**Comment by albuch** [comment]
You can set `dependencyCheckAssemblyAnalyzerEnabled := Option(False)` in your build.sbt to deactivate the Analyzer. You can find all available settings in the projects [README](https://github.com/albuch/sbt-dependency-check/blob/master/README.md).

**Comment by himnsuk** [comment]
> You can set `dependencyCheckAssemblyAnalyzerEnabled := Option(False)` in your build.sbt to deactivate the Analyzer. You can find all available settings in the projects [README](https://github.com/albuch/sbt-dependency-check/blob/master/README.md).

Thanks it worked!
