### ISSUE TITLE
Upgrade to dependency-check 2.0.0

### ISSUE THREAD

**Issue by jeremylong** [albuch/sbt-dependency-check#16]
When upgrading to use dependency-check-core:2.0.0 the call to generate the report needs to be updated.  Specifically, the plugin should not use the `ReportGenerator`. The report generation should be done via the `Engine.writeReports()`.

**Comment by albuch** [comment]
Thanks @jeremylong for the heads up. 
Is there a list (of issues) with the relevant interface and configuration changes for this version for third-party projects? This would help in spotting the needed changes easily without the need to guess them from the end-user release notes. 
I know that @stevespringett keeps a close look on the core library but maybe this would help him too for maintaining the Jenkins plug-in.
If there's no such thing than maybe adding tags to issues could help for this in the future?
