### ISSUE TITLE
dependencyCheckYarnAuditAnalyzerEnabled set to Some(false) does not have any effect

### ISSUE THREAD

**Issue by iadcode** [albuch/sbt-dependency-check#163]
#### Describe the bug
Setting dependencyCheckYarnAuditAnalyzerEnabled to Some(false) does not seem to have any effect on whether the Yarn audit Analyser is run or not.

#### Version of sbt-dependency-check used
3.1.0

#### Expected behavior
dependencyCheckYarnAuditAnalyzerEnabled when set to Some(false) will cause the Yarn audit to not be run.

#### Additional context
My project has a yarn component but at the moment there seems to be some problems which cause dependencyCheck itself to not be able to access my yarn executable (I could still call yarn directly from the command line). While trying to sort out this problem. I tried to at least turn off the Yarn analyzer to allow the rest of the reports to go through, only to realise the key does not work.

Had a look through the plugin code base and I realise the key isn't actually used anywhere apart from where it's declared and where the default is set. When setting the parameter ANALYZER_YARN_AUDIT_ENABLED in src/main/scala/net/vonbuchholtz/sbt/dependencycheck/DependencyCheckListSettingsTask.scala, the code actually refers to another key dependencyCheckNodeAuditSkipDevDependencies (line 83 on the current master HEAD 12f29983ef67724954d20722d55c6c3c7adedb90).

**Comment by albuch** [comment]
Thanks for pointing out this bug. The proposed change form the pull request however won't fix your issue as it only fixes printing the correct value of the setting when calling `dependencyCheckListSettings`.
I'll push a fix shortly that covers both issues and cut a release once all other pull requests are merged.

**Comment by iadcode** [comment]
Thanks @albuch. I see what you mean now.
