### ISSUE TITLE
Skip vulnerabilities scan

### ISSUE THREAD

**Issue by andeliero** [albuch/sbt-dependency-check#218]
Hello, could be possible to skip the vulnerabilities scan for a specific dependency or at least throw a warning?

**Comment by albuch** [comment]
Hi @andeliero, 
you can use the suppression.xml file to ignore certain pakcages, files or CVEs. Please check the docs of the core library for details of the file format: https://jeremylong.github.io/DependencyCheck/general/suppression.html 
YOu can pass teh file location to `sbt-dependecy-check` with the `dependencyCheckSuppressionFiles` Setting.

**Comment by andeliero** [comment]
Danke schön
