### ISSUE TITLE
Error when updating sbt-dependency-check above 3.1.3 with sbt 1.2.8

### ISSUE THREAD

**Issue by hmarzooq** [albuch/sbt-dependency-check#234]
Hi.

We're using `sbt.version=1.2.8`, and `sbt-dependency-check` with version `3.1.3`. But as soon we update `sbt-dependency-check `to anything above `3.1.3` - below error is thrown.

```
[error] java.lang.NoSuchMethodError: sbt.package$.fileJsonFormatter()Lsjsonnew/JsonFormat;
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckKeys.dependencyCheckSuppressionFiles(DependencyCheckKeys.scala:22)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckKeys.dependencyCheckSuppressionFiles$(DependencyCheckKeys.scala:22)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$autoImport$.dependencyCheckSuppressionFiles$lzycompute(DependencyCheckPlugin.scala:23)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$autoImport$.dependencyCheckSuppressionFiles(DependencyCheckPlugin.scala:23)
```
Could you please advise what could be the reason? As we want to use OWASP 6.5.3 version to scan our play framework based application project. It would be difficult for us to update sbt version above 1.2.8.

Thank you!

**Comment by albuch** [comment]
Hi @hmarzooq,
that is quite strange, as this was fixed in 2019 (#87) almost 2,5 years ago. And our test suite still works properly running the latest release (and all before that) with sbt v1.2.8 and we're building against that version as well.
I'll do some local testing and see if I can find anything.

**Comment by hmarzooq** [comment]
Hi @albuch I did read this thread before posting. My assumption was same that it shouldn't be occurring again after 1.3.3.

**Comment by albuch** [comment]
Issue is fixed now and I'll prepare a release soon.
