### ISSUE TITLE
Namespace tasks

### ISSUE THREAD

**Issue by joprice** [albuch/sbt-dependency-check#3]
A task name like 'check' could easily clash with a user defined one of the same name or from another plugin. There are some notes here on best naming best practices for plugins, where a plugin-specific prefix is suggested: http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html#Avoid+namespace+clashes

**Comment by albuch** [comment]
Thanks for reporting the issue. I've implemented the best-practice for the settings but forgot to do so for the tasks. I'll fix it for the next release.
