### ISSUE TITLE
Format for dependencyCheckSuppressionFile

### ISSUE THREAD

**Issue by IgorWolkov** [albuch/sbt-dependency-check#4]
Could you please provide an example of format for dependencyCheckSuppressionFile file?
Thank you.

**Comment by albuch** [comment]
Please have a look at the dependency-check core library documentation: http://jeremylong.github.io/DependencyCheck/general/suppression.html

If you choose to generate an HTML report via `dependencyCheckFormat := "HTML"` or ``dependencyCheckFormat := "ALL"` you will find buttons to generate the suppression file content as well in the HTML report.

**Comment by jeremylong** [comment]
Note, the generate button in the HTML report only uses sha1 hashes,  there
are more options for creating a suppression file that might work better
long term (due to version upgrades). See the link Alex pointed out.

**Comment by IgorWolkov** [comment]
@albuch, @jeremylong thank you!
