### ISSUE TITLE
Update versions of `sbt-dependency-graph` and `commons-collections`

### ISSUE THREAD

**Issue by mrtnrdl** [albuch/sbt-dependency-check#54]
Checking available updates via dependencyUpdates, I've seen that `sbt-dependency-graph` has a new version. (0.9.2)

In addition to that, `commons-collections` also has a new version (20040616)

**Comment by mrtnrdl** [comment]
the `commons-collections` version does produce a warning though. 

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]
[warn] 	* commons-collections:commons-collections:20040616 is selected over 3.2.1
[warn] 	    +- org.apache.velocity:velocity:1.7                   (depends on 3.2.1)
[warn] 	    +- net.vonbuchholtz:sbt-dependency-check:0.2.9-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13) (depends on 3.2.1)
[warn]
```

**Comment by albuch** [comment]
Thanks for the PR. 
The commons-collection version being reported as an update is a false postive. It is probably an issue with not being a Semver version string. The latest available version under the groupID "commons-collection" is 3.2.2
