### ISSUE TITLE
Global settings for dependencyCheck

### ISSUE THREAD

**Issue by tkriik** [albuch/sbt-dependency-check#58]
Hi, 

while it's clear from the documentation how to override settings for the dependency-check tool on a project-specific basis, I cannot seem to figure out, how to set settings (for example, the output format) globally.

In my home SBT directory I have the dependencyCheck plugin enabled, but is there also a way set the settings globally?

**Comment by albuch** [comment]
You need to 
1. Add the plugin at `~/sbt/1.0/plugins/sbt-dependency-check.sbt`
    ```
    addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "0.2.8")
    ```
1. Add the settings at `~/.sbt/1.0/global.sbt` using their fully qualified name (including the package and nested object structure)
    ```
    net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin.autoImport.dependencyCheckFormat := "All"
   ```

For further information about global settings and plugins have a look at the sbt docs: https://www.scala-sbt.org/1.x/docs/Global-Settings.html

I'll keep this issue open until I've updated the docs.
