### ISSUE TITLE
Prepare for v5.0.0-M3 release

### ISSUE THREAD

**Issue by albuch** [albuch/sbt-dependency-check#70]
https://github.com/jeremylong/DependencyCheck/compare/v5.0.0-M1...v5.0.0-M3

- [x] Rename Mono to .NET Core
- [x] New format options (JUNIT->failOption, List)
- [x] RetireJS is not experimental anymore, URL to Feed
- [x] JSON Feeds, NVD Meta data (setting)
- [x] New ossindexAnalyzer
- [x] nonProxyHosts Setting?

**Comment by jeremylong** [comment]
I am expecting to release 5.0.0 in the next 2 weeks unless anything critical comes up.  Sorry this has taken so long.
