### ISSUE TITLE
Incorrect setting name in documentation

### ISSUE THREAD

**Issue by rafaelmagu** [albuch/sbt-dependency-check#76]
Simple bug found with the documentation: `dependencyCheckJUnitFailOnCVSS` should be `dependencyCheckJUnitFailBuildOnCVSS` (see the missing word `Build`)

In:

- list of settings https://github.com/albuch/sbt-dependency-check/blob/bfcf11512030b5c5e5922d47e8578e1e666d69bd/README.md#L53
- help message https://github.com/albuch/sbt-dependency-check/blob/c5b38dfdcce8ebb7f4e61c2e5db63eb1165ad37b/src/main/scala/net/vonbuchholtz/sbt/dependencycheck/DependencyCheckKeys.scala#L11

**Comment by albuch** [comment]
Thanks for the report!
