### ISSUE TITLE
Unable to download NVCDE meta file

### ISSUE THREAD

**Issue by ronniegane** [albuch/sbt-dependency-check#83]
After adding the plugin to my project and running for the first time, I encounter the following error:
```
[error]         Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta
[error]         No documents exist
```

I am using version 1.3.0 of the plugin, in a project that is using SBT 0.13.11 (it's a Play framework 2.5.8 project). It was installed simply with the `addSbtPlugin` line added to `plugins.sbt` suggested in the readme.

Running on Ubuntu 18.04LTS.

The stack trace mentions some SSL errors:
```
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; unable to connect.
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I am perfectly able to visit https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta in a browser, and don't see any certificate errors that way.

Full output of `sbt dependencyCheck`: https://gist.github.com/ronniegane/e1913344b0aec7c249cd8fc2f8dce548

**Comment by albuch** [comment]
Hi @ronniegane , thanks for your report. It seems something on the side of NVD changed recently in the way they deliver their certs and your JVM can't handle the cert due to missing root/intermediate certificates.
Please have a look at https://github.com/jeremylong/DependencyCheck/issues/2222 and other occurrences: https://github.com/jeremylong/DependencyCheck/issues?utf8=%E2%9C%93&q=is%3Aissue+PKIX+path+building+failed for details on how to proceed.

**Comment by albuch** [comment]
The issue got resolved by NIST and there is a documented workaround at https://github.com/jeremylong/DependencyCheck/issues/2222 for future occurrences. Closing this issue.

**Comment by SCKelemen** [comment]
This is still an issue for me, if with the upstream workaround

**Comment by albuch** [comment]
Hi @SCKelemen 
the most reliable and recommended solution to network/connectivity issues is to build your own internal mirror of the NVD feeds.
That way your build pipelines will still work even when NVD has issues. You can have a look at https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html how to set that up.

We can't do anything on the plugin side which isn't under our control I'm afraid.
